### ISSUE TITLE
Controlloing multiple PTZ-camera controller

### ISSUE THREAD

**Issue by heartcored98** [ArduCAM/PTZ-Camera-Controller#2]
Hi, I am really satisfying with the PTZ camera and having fun. 

However, I would like to control two PTZ camera simultaneously on raspberry pi cm3 module, but having a problem due to the i2c and bus communication.

I enabled bus3 i2c channel with the following guide by adding 
`dtoverlay=i2c-gpio,bus=3,i2c_gpio_delay_us=1,i2c_gpio_sda=17,i2c_gpio_scl=27`  

And check that bus1 and bus3 i2c are enabled by `sudo i2cdetect -l`.  

Then, I tried to initialize the focuser instance with `smbus.SMBus(3)` for bus 3. But it does not work well. 

Do you have any advice for this problem? Or I would appreciate if you suggest other way to control two PTZ camera.

**Comment by UCTRONICS** [comment]
@heartcored98 
I have not tested it using i2c bus3 on CM3 module.  I will test  it when I am free.

**Comment by heartcored98** [comment]
Sorry for late reply, I turned it off and on again. Both i2c bus work together well.
